#!/bin/bash
# HepSim toolkit. S.Chekanov (ANL) 
# Task: Extract meta information  

export HEPSIM_DIR=$(dirname $0)

if which java >/dev/null; then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo "No java detected! Please install it from https://java.com/download"; exit 0
fi

FILE="$@"

if [ "${FILE##*.}" = "promc" ]; then
        $_java -Xms1024m -Xmx1024m -cp $HEPSIM_DIR/browser_promc.jar hepsim.Meta "$@"
fi

if [ "${FILE##*.}" = "proio" ]; then
        $_java -Xms1024m -Xmx1024m -cp $HEPSIM_DIR/browser_proio.jar hepsimproio.Meta "$@"
fi

