#!/bin/bash
# HepSim toolkit. S.Chekanov (ANL) and contributors.  
# Task: View ProIO files using ProIO browser developed by Jose Alcaraz (NIU) 

export HEPSIM_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export MAXMEM=1024

if which java >/dev/null; then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo "No java detected! Please install it from https://java.com/download"; exit 0
fi


if [ "$#" -ne 1 ]; then
    echo "Pass the file name on the local disk (or http) to browser events"
    $_java -cp $HEPSIM_DIR/browser_proio.jar:. proio.proio_browser 
    exit 0; 
fi


MFILE=$1

if [[  "${MFILE##*.}" = "proio" ]]
then
   echo "ProIO Monte Carlo file was found. Wait.."
   $_java -cp $HEPSIM_DIR/browser_proio.jar:. proio.proio_browser "$@"
fi




